### ISSUE TITLE
桃太郎の物語のページを作ります。

### ISSUE THREAD

**Issue by saitoyuka** [mwed-study-group/sample_momotaro_static_5#1]
桃太郎の誕生から、鬼退治までの物語を作ります。

**Comment by imaizumiayumi** [comment]
@saitoyuka 
では、齊藤さんは桃太郎の誕生から仲間を集めるまでのお話を作ってください！
私は鬼ヶ島に到着してから鬼退治までのお話を作ります！

**Comment by imaizumiayumi** [comment]
むかしむかし、あるところに、おじいさんとおばあさんが住んでいました。
おじいさんは山へしばかりに、おばあさんは川へせんたくに行きました。
おばあさんが川で洗濯をしていると、ドンブラコ、ドンブラコと、大きな桃が流れてきました。
「おや、これは良いおみやげになるわ」
おばあさんは大きな桃をひろいあげて、家に持ち帰りました。
そして、おじいさんとおばあさんが桃を食べようと桃を切ってみると、なんと、中から元気の良い男の赤ちゃんが飛び出してきました。
「これはきっと、神さまがくださったにちがいない」
子どものいなかったおじいさんとおばあさんは、大喜びです。
桃から生まれた男の子を、おじいさんとおばあさんは桃太郎と名付けました。
桃太郎はスクスク育って、やがて強い男の子になりました。
そしてある日、桃太郎が言いました。
「ぼく、鬼ヶ島(おにがしま)へ行って、わるい鬼を退治します」
そして、おばあさんにきび団子を作ってもらうと、鬼ヶ島へ出かけました。
旅の途中で、イヌに出会いました。
「桃太郎さん、どこへ行くのですか？」
「鬼ヶ島へ、鬼退治に行くんだ」
「それでは、お腰に付けたきび団子を１つ下さいな。おともしますよ」
イヌはきび団子をもらい、桃太郎のおともになりました。
そして、こんどはサルに出会いました。
「桃太郎さん、どこへ行くのですか？」
「鬼ヶ島へ、鬼退治に行くんだ」
「それでは、お腰に付けたきび団子を１つ下さいな。おともしますよ」
そしてこんどは、キジに出会いました。
「桃太郎さん、どこへ行くのですか？」
「鬼ヶ島へ、鬼退治に行くんだ」
「それでは、お腰に付けたきび団子を１つ下さいな。おともしますよ」
こうして、イヌ、サル、キジの仲間を手に入れた桃太郎は、ついに鬼ヶ島へやってきました。

鬼ヶ島では、鬼たちが近くの村からぬすんだ宝物やごちそうをならべて、酒盛りの真っ最中です。
「みんな、ぬかるなよ。それ、かかれ！」
イヌは鬼のおしりにかみつき、サルは鬼のせなかをひっかき、キジはくちばしで鬼の目をつつきました。
そして桃太郎も、刀をふり回して大あばれです。
とうとう鬼の親分が、
「まいったぁ、まいったぁ。こうさんだ、助けてくれぇ」
と、手をついてあやまりました。
桃太郎とイヌとサルとキジは、鬼から取り上げた宝物をくるまにつんで、元気よく家に帰りました。
おじいさんとおばあさんは、桃太郎の無事な姿を見て大喜びです。
そして三人は、宝物のおかげでしあわせにくらしましたとさ。

おしまい
